import { BufferGeometry, Float32BufferAttribute } from 'three';
import { RIFT_DEFAULTS, riftSeed, type RiftConfig } from './RiftreaverConfig';
type Point = readonly [number,number,number];
/** Teeth are fixed at build time; animation separates these paths rather than resampling them. */
export function riftBoundary(t:number,side:number,c:RiftConfig=RIFT_DEFAULTS):Point {
  const belly=Math.pow(Math.max(.003,Math.sin(Math.PI*t)),.72);
  const center=Math.sin(t*13)*.36+Math.sin(t*29)*.15;
  const tooth=1+c.jaggedness*(Math.sin(t*67+side*3)*.65+Math.sin(t*113)*.35);
  return [center+side*(.025+c.width*.5*belly*tooth),t*c.height,.18*Math.sin(t*41+side*4)];
}
function finish(pos:number[],uv:number[]=[]):BufferGeometry {
  const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(pos,3));
  if(uv.length)g.setAttribute('uv',new Float32BufferAttribute(uv,2));
  g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();return g;
}
/** Closed four-sided irregular sweep, nonindexed for hard triangle normals. */
function sweep(points:Point[],widths:number[],depths:number[]):BufferGeometry {
  const rings:Point[][]=points.map((p,i)=>[
    [p[0]-widths[i],p[1],p[2]], [p[0],p[1],p[2]-depths[i]],
    [p[0]+widths[i],p[1],p[2]], [p[0],p[1],p[2]+depths[i]],
  ]);
  const pos:number[]=[], triangle=(a:Point,b:Point,c:Point)=>pos.push(...a,...b,...c);
  for(let i=0;i<rings.length-1;i++)for(let j=0;j<4;j++){
    const k=(j+1)%4;triangle(rings[i][j],rings[i+1][j],rings[i][k]);triangle(rings[i][k],rings[i+1][j],rings[i+1][k]);
  }
  triangle(rings[0][0],rings[0][1],rings[0][2]);triangle(rings[0][0],rings[0][2],rings[0][3]);
  const r=rings[rings.length-1];triangle(r[0],r[2],r[1]);triangle(r[0],r[3],r[2]);
  return finish(pos);
}
export function createRiftEdge(segments:number,side:number,c:RiftConfig):BufferGeometry {
  const points:Point[]=[],w:number[]=[],d:number[]=[];
  for(let i=0;i<=segments;i++){const t=i/segments;points.push(riftBoundary(t,side,c));const taper=.15+.85*Math.pow(Math.sin(Math.PI*t),.5);w.push(c.edgeThickness*taper*(.7+riftSeed(i+side*19)*.7));d.push((c.edgeThickness*2+.25)*taper);}
  return sweep(points,w,d);
}
/** Recessed, curved membrane with actual side walls, five columns spanning both boundary paths. */
export function createRiftInterior(segments:number,c:RiftConfig):BufferGeometry {
  const pos:number[]=[],uv:number[]=[],rows:Point[][]=[];
  for(let i=0;i<=segments;i++){const t=i/segments,a=riftBoundary(t,-1,c),b=riftBoundary(t,1,c);const row:Point[]=[];
    for(let j=0;j<=6;j++){const f=j/6;row.push([a[0]*(1-f)+b[0]*f,t*c.height,a[2]*(1-f)+b[2]*f-c.depth*Math.pow(Math.sin(f*Math.PI),.6)]);}rows.push(row);
  }
  const tri=(i:number,j:number,ii:number,jj:number,iii:number,jjj:number)=>{pos.push(...rows[i][j],...rows[ii][jj],...rows[iii][jjj]);uv.push(j/6,i/segments,jj/6,ii/segments,jjj/6,iii/segments);};
  for(let i=0;i<segments;i++)for(let j=0;j<6;j++){tri(i,j,i,j+1,i+1,j);tri(i,j+1,i+1,j+1,i+1,j);}return finish(pos,uv);
}
export function createDimensionalSlashGeometry(segments=16):BufferGeometry {
  const p:Point[]=[],w:number[]=[],d:number[]=[];
  for(let i=0;i<=segments;i++){const t=i/segments,shape=Math.pow(Math.max(.001,Math.sin(t*Math.PI)),.65);p.push([.22*Math.sin(t*Math.PI*2)+(i%2?.07:-.07)*shape,t-.5,0]);w.push(.23*shape);d.push(.1*shape);}
  return sweep(p,w,d);
}
export function createRiftShard(seed:number):BufferGeometry {
  const p:Point[]=[],w:number[]=[],d:number[]=[];
  for(let i=0;i<4;i++){const t=i/3;p.push([.15*(riftSeed(seed+i)-.5),t-.5,.13*(riftSeed(seed+10+i)-.5)]);const s=i===0||i===3?.025:.2+riftSeed(seed+i)*.2;w.push(s);d.push(s*(.35+riftSeed(seed+20+i)*.65));}return sweep(p,w,d);
}
export function createRiftResources(c:RiftConfig) {
  return { tiers:[24,40,60].map(n=>({left:createRiftEdge(n,-1,c),right:createRiftEdge(n,1,c),interior:createRiftInterior(n,c),glowLeft:createRiftEdge(n,-1,{...c,edgeThickness:c.edgeThickness*.12}),glowRight:createRiftEdge(n,1,{...c,edgeThickness:c.edgeThickness*.12})})),slash:createDimensionalSlashGeometry(),shards:[3,17,91].map(createRiftShard) };
}
export type RiftResources = ReturnType<typeof createRiftResources>;
export function disposeRiftResources(r:RiftResources):void {r.tiers.forEach(t=>{t.left.dispose();t.right.dispose();t.interior.dispose();t.glowLeft.dispose();t.glowRight.dispose();});r.slash.dispose();r.shards.forEach(g=>g.dispose());}
// Vector3 is exported through no state; explicit normals are generated by Three's cross products.
