import '../src/styles/game.css';
import { Game } from '../src/game/Game';
import { InstancedMesh,Mesh,PointLight,Vector3 } from 'three';
import type { Ability,AbilityCastContext } from '../src/abilities/Ability';
import type { QualityPreset } from '../src/quality/QualityPreset';
const root=document.querySelector<HTMLElement>('#app')!, query=new URLSearchParams(location.search), originalFavorites=localStorage.getItem('elemental-favorites'),game=new Game(root),r=game.renderer.renderer;
const id=query.get('spell')??'tidal-serpent',report=document.createElement('pre');report.id='bending-report';report.style.cssText='position:fixed;left:24px;top:130px;max-height:60vh;overflow:auto;background:#06121ce8;color:#c6ddd7;font:11px monospace;padding:10px;z-index:40';root.append(report);
const lines:string[]=[];let errors=0,disposed=false;const check=(ok:boolean,s:string)=>{lines.push(`${ok?'PASS':'FAIL'} ${s}`);if(!ok)errors++;report.textContent=lines.join('\n');};
window.addEventListener('error',e=>check(false,e.message));window.addEventListener('unhandledrejection',e=>check(false,String(e.reason)));r.debug.onShaderError=(gl,_p,v,f)=>check(false,`GLSL ${gl.getShaderInfoLog(v)} ${gl.getShaderInfoLog(f)}`);
const frame=()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve())),frames=async(n=3)=>{for(let i=0;i<n;i++)await frame();};
const click=(s:string)=>root.querySelector<HTMLElement>(s)!.click(),key=(code:string,type='keydown')=>window.dispatchEvent(new KeyboardEvent(type,{code,bubbles:true}));
const counts=()=>{let objects=0,lights=0;game.sceneManager.scene.traverse(o=>{objects++;if(o instanceof PointLight)lights++;});return {objects,lights,geometries:r.info.memory.geometries,textures:r.info.memory.textures,programs:r.info.programs?.length,subs:game.settings.subscriberCount,effects:game.effects.activeCount,ripples:game.world.water.interactions.activeCount};};
const finite=()=>{let ok=true;game.sceneManager.scene.traverse(o=>{ok&&=[...o.position.toArray(),...o.scale.toArray(),...o.quaternion.toArray()].every(Number.isFinite);if(o instanceof Mesh)ok&&=Array.from(o.geometry.getAttribute('position').array).every(Number.isFinite);if(o instanceof InstancedMesh)ok&&=o.count<=o.instanceMatrix.count&&Array.from(o.instanceMatrix.array).every(Number.isFinite);});return ok;};
const context=(range=24):AbilityCastContext=>{const target=new Vector3(game.player.position.x,0,game.player.position.z-range);return {player:game.player,scene:game.sceneManager.scene,camera:game.camera.camera,origin:game.player.visual.getRightHandWorldPosition(),direction:new Vector3(0,0,-1),cameraForward:new Vector3(0,0,-1),playerForward:game.player.getForward().clone(),targetPoint:target,groundTarget:target,targeting:game.targeting,quality:game.settings,effectManager:game.effects,water:game.world.water.interactions,time:0,cameraFeedback:game.camera.addFeedback};};
try{
  await game.player.visual.ready;game.settings.setPreset((query.get('quality')??'LOW') as QualityPreset);game.start();await frames(12);
  const slots=JSON.stringify(game.abilities.slots.slice(0,32)),ability=game.abilities.registry.get(id)!;check(!!ability,'Registered '+id);check(game.abilities.registry.all.length===Number(query.get('roster')??36),'Expected roster count');
  for(let i=0;i<600&&(ability as Ability & {prepared?:boolean}).prepared===false;i++)await frame();
  check((ability as Ability & {prepared?:boolean}).prepared!==false,'Optional idle shader preparation completed');
  click('[data-open-book]');await frames();check(root.querySelectorAll('.spell-card').length===game.abilities.registry.all.length,'Dynamic Spellbook cards');
  const search=root.querySelector<HTMLInputElement>('[aria-label="Search spells"]')!;search.value=ability.subtitle!;search.dispatchEvent(new Event('input'));check(!root.querySelector<HTMLElement>(`[data-spell="${id}"]`)!.closest<HTMLElement>('.spell-card')!.hidden,'Subtitle search');
  root.querySelectorAll<HTMLButtonElement>('[data-favorite]').forEach(b=>{if((b.getAttribute('aria-pressed')==='true')!==(b.dataset.favorite===id))b.click();});click(`[data-spell="${id}"]`);await frames();check(game.effects.activeCount===0,'Equip does not cast');
  click('[data-open-wheel]');await frames();click(`[aria-label="Select ${ability.name}"]`);await frames();check(game.abilities.selectedAbility?.id===id,'Favorite and Quick Wheel selection');
  r.domElement.dispatchEvent(new MouseEvent('mousedown',{button:0,bubbles:true}));await frames();r.domElement.dispatchEvent(new MouseEvent('mouseup',{button:0,bubbles:true}));check(game.effects.activeCount===1,'Actual left-click cast');check(game.abilities.getCooldownById(id)>0,'Cooldown starts');check(!game.abilities.cast(context()),'Cooldown rejects duplicate');
  const phases=new Set<string>(),intervals:number[]=[];let previous=performance.now(),calls=0,triangles=0,particles=0,instances=0,contacts=0,valid=true,handGap=Infinity;const handCheck=new Vector3();
  for(let i=0;i<1400&&game.effects.activeCount;i++){await frame();const now=performance.now();intervals.push(now-previous);previous=now;game.sceneManager.scene.children.forEach(o=>{if(o.userData.bendingId===id){phases.add(String(o.userData.phase));if(['draw','gather','assemble','weave'].includes(String(o.userData.phase))&&o.userData.castOrigin instanceof Vector3)handGap=Math.min(handGap,o.userData.castOrigin.distanceTo(game.player.visual.getRightHandWorldPosition(handCheck)));contacts=Math.max(contacts,Number(o.userData.contacts??0));}});calls=Math.max(calls,r.info.render.calls);triangles=Math.max(triangles,r.info.render.triangles);particles=Math.max(particles,game.effects.particleCount);instances=Math.max(instances,game.effects.instanceCount);if(i%30===0)valid&&=finite();}
  check(phases.size>=3,'Realtime authored stages '+[...phases].join('/'));check(handGap<.05,'Actual animated casting-hand origin');check(contacts===(id==='skybreaker'?3:1),'Visible contact events');check(valid&&r.getContext().getError()===0,'Finite geometry and WebGL NO_ERROR');check(game.effects.activeCount===0,'Natural completion');await frames(15);check(game.world.water.interactions.activeCount===0,'Owned water effects removed');
  intervals.sort((a,b)=>a-b);lines.push('PROFILE '+JSON.stringify({id,quality:game.settings.preset,viewport:[innerWidth,innerHeight],calls,triangles,particles,instances,rafMedian:intervals[Math.floor(intervals.length*.5)],rafP95:intervals[Math.floor(intervals.length*.95)],rafMax:intervals.at(-1)}));
  for(const distance of [6,100]){game.abilities.update(20);check(game.abilities.cast(context(distance)),`${distance}m aim accepted safely`);for(let i=0;i<120&&game.effects.activeCount;i++){game.effects.update(.05,i*.05);game.renderer.render();await frame();}check(!game.effects.activeCount&&finite()&&r.getContext().getError()===0,'Near/clamped-far lifecycle');}
  if(query.has('stress')){const before=counts();for(let cast=0;cast<10;cast++){game.abilities.update(20);check(game.abilities.cast(context()),'Repeated cast '+(cast+1));for(let i=0;i<120&&game.effects.activeCount;i++){game.effects.update(.05,i*.05);game.renderer.render();await frame();}await frames(3);check(JSON.stringify(counts())===JSON.stringify(before),'Warmed resource baseline '+(cast+1));}lines.push('COUNTS '+JSON.stringify({before,after:counts()}));}
  game.abilities.update(20);game.abilities.cast(context());for(const quality of ['LOW','MEDIUM','MAX'] as const){game.settings.setPreset(quality);await frames(3);check(finite()&&r.getContext().getError()===0,'Live '+quality);}game.effects.update(120,120);
  key('KeyW');key('ShiftLeft');await frames(45);game.abilities.update(20);check(game.abilities.cast(context()),'Moving cast');await frames(8);check(game.player.visual.animationState==='Run'&&game.player.visual.motion?.castPhase!=='READY','Gesture preserves sprint');key('KeyW','keyup');key('ShiftLeft','keyup');game.effects.update(120,120);await frames(240);check(game.player.visual.animationState==='Idle'&&game.player.visual.motion?.castPhase==='READY','Gesture returns to Idle/READY');
  await frames(240);check(game.player.visual.animationState==='Idle'&&game.player.visual.motion?.castPhase==='READY','Extended recovery reaches Idle/READY');
  check(JSON.stringify(game.abilities.slots.slice(0,32))===slots,'Original 32 slots unchanged');game.dispose();disposed=true;check(r.info.memory.geometries===0&&r.info.memory.textures===0&&game.settings.subscriberCount===0,'Full game GPU/subscription teardown');check(errors===0,'BENDING BROWSER COMPLETE');
}catch(e){check(false,String(e));if(!disposed){game.dispose();disposed=true;}}
const restore=()=>{if(originalFavorites===null)localStorage.removeItem('elemental-favorites');else localStorage.setItem('elemental-favorites',originalFavorites);};restore();report.dataset.complete='true';report.textContent=lines.join('\n');window.addEventListener('pagehide',()=>{restore();if(!disposed)game.dispose();});
