import { test,expect } from '@playwright/test';
import { Mesh,InstancedMesh,PerspectiveCamera,Scene,Vector3 } from 'three';
import { Player } from '../src/player/Player';
import { EffectManager } from '../src/effects/EffectManager';
import { GraphicsSettings } from '../src/quality/GraphicsSettings';
import { WaterInteractionManager } from '../src/world/water/WaterInteractionManager';
import { TargetingSystem } from '../src/targeting/TargetingSystem';
import type { Ability,AbilityCastContext } from '../src/abilities/Ability';
import { AbilityManager } from '../src/abilities/AbilityManager';
import { TidalSerpent } from '../src/abilities/tidalSerpent/TidalSerpent';
import { TIDAL_BUDGETS } from '../src/abilities/tidalSerpent/TidalSerpentConfig';
import { SweptVolume } from '../src/abilities/bending/SweptVolume';
import { acquireBending,bendingTarget } from '../src/abilities/bending/BendingSupport';
import { matchesSpell,spellCategory } from '../src/ui/SpellCatalog';
export function bendContext():AbilityCastContext{const scene=new Scene(),player=new Player(scene),water=new WaterInteractionManager();water.setHeightSampler((x,z)=>.2+Math.sin(x*.1+z*.2)*.1);const target=new Vector3(0,0,-24);return {scene,player,water,camera:new PerspectiveCamera(),origin:new Vector3(0,1.3,0),direction:new Vector3(0,0,-1),playerForward:new Vector3(0,0,-1),cameraForward:new Vector3(0,0,-1),groundTarget:target,targetPoint:target,targeting:new TargetingSystem(scene),quality:new GraphicsSettings(),effectManager:new EffectManager(),time:0};}
export function cleanBend(c:AbilityCastContext,a:Ability){c.effectManager.dispose();a.dispose?.();c.player.dispose();c.water?.dispose();c.targeting.dispose();c.quality.dispose();}
test('Elliptical swept topology stays closed, finite, normalized and volumetric while curve changes',()=>{const s=new SweptVolume(40,10);for(let frame=0;frame<10;frame++){s.update((t,p)=>p.set(Math.sin(t*6+frame)*t,Math.sin(t*3)*2,-t*15),t=>.04+Math.sin(t*Math.PI)*.5);const g=s.geometry,p=g.getAttribute('position'),n=g.getAttribute('normal');expect([...p.array,...n.array].every(Number.isFinite)).toBe(true);for(let i=0;i<n.count;i++)expect(new Vector3().fromBufferAttribute(n,i).length()).toBeCloseTo(1,4);expect(g.boundingSphere!.radius).toBeGreaterThan(7);const edges=new Map<string,number>(),idx=g.index!;for(let i=0;i<idx.count;i+=3)for(let j=0;j<3;j++){const a=idx.getX(i+j),b=idx.getX(i+(j+1)%3),k=[a,b].sort((x,y)=>x-y).join(':');edges.set(k,(edges.get(k)??0)+1);}expect([...edges.values()].every(n=>n===2)).toBe(true);}s.dispose();});
test('Water budgets and shared admission are finite and releases idempotent',()=>{expect(TIDAL_BUDGETS.map(q=>q.particles)).toEqual([180,430,900]);const m=new EffectManager(),a=acquireBending(m)!,b=acquireBending(m)!,c=acquireBending(m)!;expect(acquireBending(m)).toBeNull();a();a();const d=acquireBending(m)!;expect(typeof d).toBe('function');b();c();d();});
test('Bending targets snapshot aim, clamp range, sample ocean and reject invalid coordinates',()=>{const c=bendContext(),a=new TidalSerpent();c.targetPoint.z=-100;const p=bendingTarget(c,28)!;expect(Math.hypot(p.x,p.z)).toBeCloseTo(28);expect(p.y).toBeCloseTo(c.water!.getSurfaceHeight(p.x,p.z));expect(c.targetPoint.z).toBe(-100);c.targetPoint.x=NaN;expect(bendingTarget(c,28)!.toArray().every(Number.isFinite)).toBe(true);c.origin.y=NaN;expect(bendingTarget(c,28)).toBeNull();cleanBend(c,a);});
test('Tidal Serpent integrates search/category/cooldown and 20 complete pooled lifecycles release water and subscriptions',()=>{const c=bendContext(),a=new TidalSerpent(),m=new AbilityManager();m.registry.register(a);m.selectAbility(a.id);expect(spellCategory(a)).toBe('WATER');expect(matchesSpell(a,'current lash','WATER')).toBe(true);const baseline=c.scene.children.length,subs=c.quality.subscriberCount;for(let cast=0;cast<20;cast++){m.update(20);expect(m.cast(c)).toBe(true);expect(m.getCooldownById(a.id)).toBe(3);expect(m.cast(c)).toBe(false);for(let i=0;i<100&&c.effectManager.activeCount;i++){c.effectManager.update(.05,i*.05);c.scene.traverse(o=>{if(o instanceof Mesh)expect(Array.from(o.geometry.getAttribute('position').array).every(Number.isFinite)).toBe(true);if(o instanceof InstancedMesh)expect(o.count).toBeLessThanOrEqual(o.instanceMatrix.count);});if(i===12)c.quality.setPreset(cast%2?'LOW':'MAX');}expect(c.effectManager.activeCount).toBe(0);expect(c.water!.activeCount).toBe(0);expect(c.scene.children.length).toBe(baseline);expect(c.quality.subscriberCount).toBe(subs);}m.dispose();cleanBend(c,a);});
