import '../src/styles/game.css';
import { Bone, Mesh, SkinnedMesh, Vector3 } from 'three';
import { Game } from '../src/game/Game';
import type { AbilityCastContext } from '../src/abilities/Ability';
import type { QualityPreset } from '../src/quality/QualityPreset';
const root=document.querySelector<HTMLElement>('#app')!,game=new Game(root),query=new URLSearchParams(location.search);
const report=document.createElement('pre');report.id='character-tests';report.style.cssText='position:fixed;left:24px;top:130px;z-index:50;font:11px monospace;color:#d0dbc3;background:#07101ae8;padding:12px;max-height:70vh;overflow:auto';root.append(report);
const lines:string[]=[],records:object[]=[];let failures=0;const check=(ok:boolean,label:string)=>{lines.push(`${ok?'PASS':'FAIL'} ${label}`);if(!ok)failures++;report.textContent=lines.join('\n')+'\nDATA '+JSON.stringify(records);};
window.addEventListener('error',e=>check(false,e.message));window.addEventListener('unhandledrejection',e=>check(false,String(e.reason)));const renderer=game.renderer.renderer;renderer.debug.onShaderError=(gl,_p,v,f)=>check(false,`GLSL ${gl.getShaderInfoLog(v)} ${gl.getShaderInfoLog(f)}`);
const frame=()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));const frames=async(n:number)=>{for(let i=0;i<n;i++)await frame();};const key=(code:string,down=true)=>window.dispatchEvent(new KeyboardEvent(down?'keydown':'keyup',{code,bubbles:true}));
const finite=()=>{let valid=true;game.player.visual.root.traverse(o=>{valid&&=[...o.position.toArray(),...o.quaternion.toArray(),...o.scale.toArray()].every(Number.isFinite);if(o instanceof Bone)valid&&=Math.abs(o.quaternion.length()-1)<.0001;});return valid;};
const metrics=()=>{let bones=0,meshes=0,triangles=0;const skeletons=new Set(),materials=new Set();game.player.visual.root.traverse(o=>{if(o instanceof Bone)bones++;if(o instanceof Mesh){meshes++;triangles+=(o.geometry.index?.count??o.geometry.getAttribute('position').count)/3;for(const m of Array.isArray(o.material)?o.material:[o.material])materials.add(m);if(o instanceof SkinnedMesh)skeletons.add(o.skeleton);}});return{bones,meshes,triangles,skeletons:skeletons.size,materials:materials.size,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,programs:renderer.info.programs?.length,subscriptions:game.settings.subscriberCount};};
const context=():AbilityCastContext=>{const origin=game.player.visual.getRightHandWorldPosition(),target=game.player.position.clone().add(new Vector3(0,0,-28));target.y=game.world.water.interactions.getSurfaceHeight(target.x,target.z);return{player:game.player,scene:game.sceneManager.scene,camera:game.camera.camera,origin,direction:target.clone().sub(origin).normalize(),targetPoint:target,groundTarget:target,playerForward:game.player.getForward().clone(),cameraForward:game.camera.camera.getWorldDirection(new Vector3()),targeting:game.targeting,effectManager:game.effects,quality:game.settings,time:0,water:game.world.water.interactions,cameraFeedback:game.camera.addFeedback};};
try{
 await game.player.visual.ready;game.settings.setPreset((query.get('quality')??'LOW')as QualityPreset);game.start();await frames(20);
 check(game.player.visual.loaded&&game.abilities.registry.all.length===36,'Actual model loaded; all 36 abilities preserved');check(metrics().bones===80&&metrics().skeletons===1&&metrics().meshes>=8,'One original 80-bone skeleton; real skinned adventurer garments');
 const animation=game.player.visual.animation!,mixer=animation.mixer,samples:number[]=[],original=game.player.visual.update.bind(game.player.visual);
 game.player.visual.update=(...args)=>{const start=performance.now();original(...args);samples.push(performance.now()-start);};
 check(game.player.visual.animationState==='Idle','Idle clip active');
 for(const codes of [['KeyW'],['KeyS'],['KeyA'],['KeyD'],['KeyW','KeyD']]){const start=game.player.position.clone();codes.forEach(c=>key(c));await frames(110);check(game.player.position.distanceTo(start)>.2&&finite(),`${codes.join('+')}: camera-relative motion and finite rig`);codes.forEach(c=>key(c,false));await frames(100);check(game.player.visual.animationState==='Idle','Deceleration blends to Idle');}
 key('KeyW');await frames(100);check(animation.activeClip==='Run'&&animation.weights.Run>.8,'4.8m/s normal locomotion blends into compatible Run');key('ShiftLeft');await frames(140);check(animation.state==='SPRINT'&&game.player.velocity.length()>7,'Shift sprint retains speed; stronger bounded lean and cadence');
 key('KeyW',false);key('KeyS');await frames(35);check(finite(),'Rapid direction reversal has finite bounded bone rotations');key('KeyS',false);key('ShiftLeft',false);await frames(180);
 key('KeyW');await frames(100);
 for(const index of [30,25,26,27,28,29]){game.effects.update(120,120);game.abilities.update(120);game.abilities.select(index);const c=context(),name=game.abilities.selectedAbility!.name;
  check(c.origin.distanceTo(game.player.visual.getRightHandWorldPosition())<1e-6,`${name}: shared origin is exact right-hand bone`);
  check(game.abilities.cast(c),`${name}: existing cast accepted`);await frames(35);check(game.player.velocity.length()>1&&animation.weights.Run>.8&&finite(),`${name}: upper-body cast preserves moving legs and targeting`);
  game.effects.update(120,120);game.world.water.interactions.update(120);for(let n=0;n<400&&game.player.visual.motion?.castPhase!=='READY';n++)await frame();check(game.player.visual.motion?.castPhase==='READY',`${name}: cast follow-through recovers`);
 }
 key('KeyW',false);await frames(180);game.world.water.interactions.update(120);game.camera.yaw+=.8;await frames(30);check(finite()&&game.targeting.aimDirection.length()>.99,'Camera orbit, head look and targeting remain finite');
 key('F3');await frames(20);key('F3',false);check(root.querySelector('.debug-panel')?.textContent?.includes('CHARACTER ANIMATION')===true,'F3 character diagnostics and existing Ocean Editor coexist');key('F3');await frames(2);key('F3',false);
 // Warm all shader/quality variants before comparing resources.
 for(let n=0;n<2;n++)for(const q of ['LOW','MEDIUM','MAX']as QualityPreset[]){game.settings.setPreset(q);await frames(12);check(finite()&&renderer.getContext().getError()===0,`${q}: valid character shaders and wave contact`);}
 for(const q of ['LOW','MEDIUM','MAX']as QualityPreset[]){game.settings.setPreset(q);await frames(15);const start=samples.length;await frames(90);const tier=samples.slice(start).sort((a,b)=>a-b);records.push({preset:q,characterUpdateMs:{median:tier[Math.floor(tier.length*.5)],p95:tier[Math.floor(tier.length*.95)],max:tier.at(-1)},calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,footIK:game.player.visual.feet?.enabled});}
 const baseline=metrics();for(let i=0;i<15;i++){game.settings.setPreset((['LOW','MEDIUM','MAX']as QualityPreset[])[i%3]);await frames(6);}const after=metrics();
 check(JSON.stringify(baseline)===JSON.stringify(after)&&animation.mixer===mixer,'15 live quality switches: no new mixers, skeletons, meshes, materials or GPU resources');
 samples.sort((a,b)=>a-b);records.push({quality:query.get('quality')??'LOW',character:after,sourceSpeeds:animation.sourceSpeeds,updateMs:{median:samples[Math.floor(samples.length*.5)],p95:samples[Math.floor(samples.length*.95)],max:samples.at(-1)},render:{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles},feet:game.player.visual.feet?.contacts});
 check(renderer.getContext().getError()===0,'Final WebGL error is zero');game.dispose();check(game.settings.subscriberCount===0&&renderer.info.memory.geometries===0&&renderer.info.memory.textures===0,'Full character/game teardown releases subscriptions and GPU resources');check(failures===0,`FINAL ${failures===0?'PASS':'FAIL'} · ${failures} failures`);
}catch(e){check(false,String(e));game.dispose();}
