import '../src/styles/game.css';
import { Game } from '../src/game/Game';
import { PointLight } from 'three';
import { OCEAN_DEFAULTS } from '../src/world/water/OceanSettings';
const root = document.querySelector<HTMLElement>('#app')!, game = new Game(root);
const report = document.createElement('pre'); report.id = 'phase25-report';
report.style.cssText = 'position:fixed;left:24px;top:145px;background:#06101ade;color:#c1d5e4;font:10px monospace;max-height:45vh;overflow:auto;z-index:40;pointer-events:none'; root.append(report);
const output: string[] = []; const check = (ok: boolean, text: string) => { output.push(`${ok ? 'PASS' : 'FAIL'} ${text}`); report.textContent = output.join('\n'); };
window.addEventListener('error', e => check(false, e.message)); window.addEventListener('unhandledrejection', e => check(false, String(e.reason)));
game.renderer.renderer.debug.onShaderError = gl => check(false, `GLSL ${gl.getError()}`);
const frame = () => new Promise<void>(resolve => requestAnimationFrame(() => resolve()));
const frames = async (n = 3) => { for (let i = 0; i < n; i++) await frame(); };
const key = (code: string, type = 'keydown', shiftKey = false) => window.dispatchEvent(new KeyboardEvent(type, {code, shiftKey, bubbles:true}));
const click = (selector: string) => root.querySelector<HTMLElement>(selector)!.click();
const counts = () => { let objects = 0, lights = 0; game.sceneManager.scene.traverse(o => {objects++; if (o instanceof PointLight) lights++;}); const r = game.renderer.renderer; return {objects, lights, geometries:r.info.memory.geometries, textures:r.info.memory.textures, subscriptions:game.settings.subscriberCount}; };
await game.player.visual.ready; game.settings.setPreset('LOW'); game.start(); await frames(12);
check(game.abilities.registry.all.length === 31, 'All 30 original abilities plus Ember Comet');
check(game.abilities.registry.all.every(a => Number.isFinite(a.range)), 'Every card uses actual range metadata');
check(getComputedStyle(root.querySelector('.ability-bar')!).display === 'none', 'Old 27-card wall hidden');
key('Tab'); key('Tab','keyup'); await frames();
check(root.querySelector<HTMLDialogElement>('.spellbook')!.open, 'Tab opens Spellbook');
check(document.activeElement?.getAttribute('aria-label') === 'Search spells', 'Search receives focus');
const selected = game.abilities.selectedIndex;
key('KeyE'); game.renderer.renderer.domElement.dispatchEvent(new MouseEvent('mousedown',{button:0,bubbles:true})); await frames(); key('KeyE','keyup');
check(game.abilities.selectedIndex === selected && game.effects.activeCount === 0, 'Overlay blocks selection shortcuts and world casting');
const search = root.querySelector<HTMLInputElement>('[aria-label="Search spells"]')!;
search.value = 'dune cleaver'; search.dispatchEvent(new Event('input'));
check(root.querySelectorAll('.spell-card:not([hidden])').length === 1, 'Subtitle search finds Sand Reaper');
search.value = ''; search.dispatchEvent(new Event('input')); click('[data-category="WATER"]');
check(root.querySelectorAll('.spell-card:not([hidden])').length >= 2, 'Water category includes original water abilities');
click('[data-category="ALL"]');
const first = game.abilities.registry.all[0];
const star = root.querySelector<HTMLButtonElement>(`[data-favorite="${first.id}"]`)!;
if (star.getAttribute('aria-pressed') !== 'true') star.click();
click(`[data-spell="${first.id}"]`); await frames();
check(!root.querySelector<HTMLDialogElement>('.spellbook')!.open && game.effects.activeCount === 0, 'Equip closes overlay without casting');
check(document.activeElement === game.renderer.renderer.domElement, 'Canvas focus restored');
key('Backquote'); await frames(); key('Backquote','keyup'); await frames();
check(!root.querySelector<HTMLDialogElement>('.quick-wheel')!.open && game.abilities.selectedIndex === 0, 'Held wheel release with no intent preserves selection');
key('Backquote'); await frames();
const heldWheel=root.querySelector<HTMLDialogElement>('.quick-wheel')!, ring=heldWheel.querySelector<HTMLElement>('.wheel-ring')!, rect=ring.getBoundingClientRect();
heldWheel.dispatchEvent(new MouseEvent('mousemove',{clientX:rect.left+rect.width*.5,clientY:rect.top+rect.height*.5,bubbles:true}));
key('Backquote','keyup'); await frames();
check(game.abilities.selectedIndex===0,'Wheel center dead zone never changes selection');
key('Backquote'); await frames();
heldWheel.dispatchEvent(new MouseEvent('mousemove',{clientX:rect.left+rect.width*.5,clientY:rect.top+rect.height*.15,bubbles:true}));
key('Backquote','keyup'); await frames();
check(game.abilities.selectedIndex===0 && !heldWheel.open,'Mouse wedge selection commits safely on key release');
click('[data-open-wheel]'); await frames(); const wheel=root.querySelector<HTMLDialogElement>('.quick-wheel')!;
wheel.dispatchEvent(new KeyboardEvent('keydown',{code:'ArrowRight',bubbles:true})); wheel.dispatchEvent(new KeyboardEvent('keydown',{code:'Enter',bubbles:true})); await frames();
check(!wheel.open && game.abilities.selectedIndex === 0, 'Wheel keyboard confirmation shares AbilityManager selection');
click('[data-open-book]'); await frames();
const originalStars=[...root.querySelectorAll<HTMLButtonElement>('[data-favorite]')].map(b=>b.getAttribute('aria-pressed')==='true');
root.querySelectorAll<HTMLButtonElement>('[data-favorite]').forEach((b,i)=>{if(i<10&&b.getAttribute('aria-pressed')!=='true')b.click();});
click('.spellbook .overlay-close'); click('[data-open-wheel]'); await frames();
check(wheel.querySelectorAll('.wheel-spell').length===8,'More than eight favorites yields exactly eight bounded wheel entries');
wheel.dispatchEvent(new Event('cancel',{cancelable:true})); await frames();
check(!wheel.open && game.effects.activeCount===0,'Wheel Escape/cancel path never casts');
click('[data-open-book]'); await frames();
root.querySelectorAll<HTMLButtonElement>('[data-favorite]').forEach((b,i)=>{if((b.getAttribute('aria-pressed')==='true')!==originalStars[i])b.click();});
click('.spellbook .overlay-close'); await frames();
game.renderer.renderer.domElement.dispatchEvent(new MouseEvent('mousedown',{button:0,bubbles:true})); await frames();
game.renderer.renderer.domElement.dispatchEvent(new MouseEvent('mouseup',{button:0,bubbles:true}));
check(game.effects.activeCount===1 && game.abilities.getCooldownById(first.id)>0,'World click casts equipped spell and starts authoritative cooldown');
click('[data-open-book]'); await frames();
check(root.querySelector(`[data-spell="${first.id}"] .spell-state`)!.textContent!.includes('RECOVERING'),'Spellbook shows live cooldown while effect is active');
const second=game.abilities.registry.all[1]; click(`[data-spell="${second.id}"]`); await frames();
check(game.abilities.selectedAbility?.id===second.id && game.effects.activeCount===1,'Selecting another spell preserves the running effect');
game.effects.update(120,120); game.abilities.update(120); await frames(240);
const before=game.player.position.clone(); key('KeyW'); await frames(20); key('KeyW','keyup');
check(game.player.position.distanceTo(before) > .05, 'WASD movement works after overlay close'); await frames(30);
const walkStart=game.player.position.clone(); key('ShiftLeft'); key('KeyW'); await frames(20); key('KeyW','keyup'); key('ShiftLeft','keyup');
check(game.player.position.distanceTo(walkStart) > .1, 'Shift sprint remains usable'); await frames(60);
check(game.targeting.getTargetPoint().toArray().every(Number.isFinite), 'Camera targeting remains finite');
key('F3'); key('F3','keyup'); await frames();
check(!root.querySelector<HTMLElement>('.ocean-editor')!.hidden, 'F3 exposes DEV ocean editor');
const amp=root.querySelector<HTMLInputElement>('[aria-label="Ocean amplitude"]')!;
amp.value='.7'; amp.dispatchEvent(new Event('input'));
check(game.world.water.settings.amplitude===.7 && game.world.water.material.uniforms.uAmplitude.value===.7, 'Editor updates live shader uniform');
game.world.water.configure(OCEAN_DEFAULTS); key('F3'); key('F3','keyup'); await frames();
const modes: unknown[]=[];
for(const preset of ['LOW','MEDIUM','MAX'] as const) {game.settings.setPreset(preset); await frames(12); modes.push({preset,waves:game.world.water.material.uniforms.uWaveCount.value,ripples:game.world.water.interactions.capacity,vertices:game.world.water.mesh.geometry.getAttribute('position').count}); check(game.renderer.renderer.getContext().getError()===0,`${preset}: no WebGL errors`);}
output.push('QUALITY '+JSON.stringify(modes)); report.textContent=output.join('\n');
const baseline=counts();
for(let i=0;i<15;i++){game.settings.setPreset(i%2?'LOW':'MAX');game.world.water.configure({amplitude:.6+i*.03,roughness:.2+i*.005});await frames(2);}
game.settings.setPreset('MAX'); game.world.water.configure(OCEAN_DEFAULTS); await frames(12);
const after=counts(); check(JSON.stringify(baseline)===JSON.stringify(after),'15 live quality/parameter changes: scene, lights, GPU geometries/textures, subscriptions stable');
output.push('COUNTS '+JSON.stringify({baseline,after})); check(game.effects.activeCount===0,'UI never creates unintended effects');
report.dataset.complete='true'; report.textContent=output.join('\n');
window.addEventListener('pagehide',()=>game.dispose());
