import '../src/styles/game.css';
import { Game } from '../src/game/Game';
import { Mesh, InstancedMesh, PointLight, Vector3 } from 'three';
import type { AbilityCastContext } from '../src/abilities/Ability';
import type { QualityPreset } from '../src/quality/QualityPreset';
const root=document.querySelector<HTMLElement>('#app')!,game=new Game(root),renderer=game.renderer.renderer,query=new URLSearchParams(location.search);
const report=document.createElement('pre');report.id='rift-report';report.style.cssText='position:fixed;left:24px;top:125px;color:#d6c6ef;background:#100b20ed;padding:10px;font:11px monospace;max-height:65vh;overflow:auto;z-index:40';root.append(report);
const lines:string[]=[];let errors=0,disposed=false;const initialFavorites=localStorage.getItem('elemental-favorites');
const check=(ok:boolean,text:string)=>{lines.push(`${ok?'PASS':'FAIL'} ${text}`);if(!ok)errors++;report.textContent=lines.join('\n');};
window.addEventListener('error',e=>check(false,e.message));window.addEventListener('unhandledrejection',e=>check(false,String(e.reason)));
renderer.debug.onShaderError=(gl,_p,v,f)=>check(false,`GLSL ${gl.getShaderInfoLog(v)} ${gl.getShaderInfoLog(f)}`);
const frame=()=>new Promise<void>(r=>requestAnimationFrame(()=>r())),frames=async(n=3)=>{for(let i=0;i<n;i++)await frame();};
const click=(s:string)=>root.querySelector<HTMLElement>(s)!.click();const key=(code:string,type='keydown')=>window.dispatchEvent(new KeyboardEvent(type,{code,bubbles:true}));
const context=(range=28):AbilityCastContext=>{const target=new Vector3(0,0,-range);return {scene:game.sceneManager.scene,player:game.player,camera:game.camera.camera,origin:game.player.visual.getRightHandWorldPosition(),direction:new Vector3(0,0,-1),playerForward:game.player.getForward().clone(),cameraForward:game.targeting.aimDirection.clone(),groundTarget:target,targetPoint:target,targeting:game.targeting,effectManager:game.effects,quality:game.settings,time:0,water:game.world.water.interactions,cameraFeedback:game.camera.addFeedback,skyFraming:game.camera.requestSkyFraming};};
const counts=()=>{let objects=0,lights=0;game.sceneManager.scene.traverse(o=>{objects++;if(o instanceof PointLight)lights++;});return {objects,lights,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,programs:renderer.info.programs?.length,subscriptions:game.settings.subscriberCount,particles:game.effects.particleCount,instances:game.effects.instanceCount,effects:game.effects.activeCount,ripples:game.world.water.interactions.activeCount};};
const finite=()=>{let valid=true;game.sceneManager.scene.traverse(o=>{valid&&=[...o.position.toArray(),...o.quaternion.toArray(),...o.scale.toArray()].every(Number.isFinite);if(o instanceof InstancedMesh)valid&&=o.count<=o.instanceMatrix.count&&Array.from(o.instanceMatrix.array).every(Number.isFinite);if(o instanceof Mesh)valid&&=Array.from(o.geometry.getAttribute('position').array).every(Number.isFinite);});return valid;};
try{
  await game.player.visual.ready;game.settings.setPreset((query.get('quality')??'LOW') as QualityPreset);game.start();await frames(15);
  const oldSlots=JSON.stringify(game.abilities.slots.slice(0,31));check(game.abilities.registry.all.length===36,'Original roster preserved; Riftreaver remains #32 in 36 abilities');
  click('[data-open-book]');await frames();check(root.querySelectorAll('.spell-card').length===36,'Spellbook automatically includes all 36');
  const search=root.querySelector<HTMLInputElement>('[aria-label="Search spells"]')!;
  for(const term of ['rift','scar','reality','void','dimensional']){search.value=term;search.dispatchEvent(new Event('input'));check(!root.querySelector<HTMLElement>('[data-spell="riftreaver"]')!.closest<HTMLElement>('.spell-card')!.hidden,`Search ${term}`);}
  click('[data-category="SHADOW / DARK"]');check(!root.querySelector<HTMLElement>('[data-spell="riftreaver"]')!.closest<HTMLElement>('.spell-card')!.hidden,'Existing VOID category');
  const card=root.querySelector<HTMLElement>('[data-spell="riftreaver"]')!.closest<HTMLElement>('.spell-card')!;check(card.textContent!.includes('55m')&&card.textContent!.includes('10s'),'Range/cooldown metadata');
  root.querySelectorAll<HTMLButtonElement>('[data-favorite]').forEach(b=>{if((b.getAttribute('aria-pressed')==='true')!==(b.dataset.favorite==='riftreaver'))b.click();});
  click('[data-spell="riftreaver"]');await frames();check(game.abilities.selectedIndex===31&&game.effects.activeCount===0,'Book equip does not cast');
  click('[data-open-wheel]');await frames();check(!!root.querySelector('[aria-label="Select RIFTREAVER"]'),'Favorites feed Quick Wheel');click('[aria-label="Select RIFTREAVER"]');await frames();check(game.abilities.selectedAbility?.id==='riftreaver','Wheel equips Riftreaver');
  renderer.domElement.dispatchEvent(new MouseEvent('mousedown',{button:0,bubbles:true}));await frames();renderer.domElement.dispatchEvent(new MouseEvent('mouseup',{button:0,bubbles:true}));
  check(game.effects.activeCount===1&&game.abilities.getCooldownById('riftreaver')>9.8,'Left-click casts with authoritative cooldown');let rejected=0;for(let i=0;i<100;i++)if(!game.abilities.cast(context()))rejected++;check(rejected===100&&game.effects.activeCount===1,'100 rapid attempts rejected');
  const stages=new Set<string>(),intervals:number[]=[];let previous=performance.now(),peakCalls=0,peakTriangles=0,peakParticles=0,peakInstances=0,handGap=Infinity,hitCount=0,valid=true;
  for(let i=0;i<2200&&game.effects.activeCount;i++){
    await frame();const now=performance.now();intervals.push(now-previous);previous=now;
    const effect=game.sceneManager.scene.getObjectByName('Riftreaver · bounded pooled fracture');if(effect){stages.add(String(effect.userData.phase));hitCount=Math.max(hitCount,Number(effect.userData.slashHits));if(effect.userData.phase==='incision'){const incision=effect.getObjectByName('Traveling incision');if(incision)handGap=Math.min(handGap,incision.position.distanceTo(game.player.visual.getRightHandWorldPosition()));}}
    peakCalls=Math.max(peakCalls,renderer.info.render.calls);peakTriangles=Math.max(peakTriangles,renderer.info.render.triangles);peakParticles=Math.max(peakParticles,game.effects.particleCount);peakInstances=Math.max(peakInstances,game.effects.instanceCount);if(i%30===0)valid&&=finite();
  }
  check(['incision','travel','opening','instability','slashes','collapse','implosion','aftermath'].every(s=>stages.has(s)),'All eight phases observed in actual realtime playback');check(handGap<.05,'Incision follows real animated right hand');check(hitCount===3,'Three sequential slash contacts observed');check(valid&&renderer.getContext().getError()===0,'Finite geometry/instances and WebGL NO_ERROR');check(game.effects.activeCount===0,'Natural realtime completion');await frames(15);check(game.world.water.interactions.activeCount===0,'Ocean owners released');
  intervals.sort((a,b)=>a-b);lines.push('PROFILE '+JSON.stringify({quality:game.settings.preset,viewport:[window.innerWidth,window.innerHeight],peakCalls,peakTriangles,peakParticles,peakInstances,rafMedian:intervals[Math.floor(intervals.length*.5)],rafP95:intervals[Math.floor(intervals.length*.95)],rafMax:intervals.at(-1)}));
  for(const range of [8,28,100]){game.abilities.update(20);check(game.abilities.cast(context(range)),`${range}m input accepted`);const phases=new Set<string>();for(let i=0;i<150&&game.effects.activeCount;i++){game.effects.update(.05,i*.05);game.renderer.render();const bundle=game.sceneManager.scene.getObjectByName('Riftreaver · bounded pooled fracture');if(bundle)phases.add(String(bundle.userData.phase));}check(phases.has('opening')&&phases.has('implosion')&&game.effects.activeCount===0,`${range}m input: travel/open/implode/cleanup`);await frames(3);}
  const initialQuality=game.settings.preset;game.abilities.update(20);check(game.abilities.cast(context()),'Live quality test begins one bounded cast');game.effects.update(1.45,1.45);
  for(const quality of ['LOW','MEDIUM','MAX','LOW',initialQuality] as const){click(`[data-quality="${quality}"]`);await frames(3);check(game.settings.preset===quality&&game.effects.activeCount===1&&finite()&&renderer.getContext().getError()===0,`Live ${quality} preserves active fracture`);}
  game.effects.update(120,120);await frames(3);
  if(query.has('stress')){const baseline=counts();for(let cast=0;cast<20;cast++){game.abilities.update(20);check(game.abilities.cast(context()),`Cast ${cast+1}`);for(let i=0;i<150&&game.effects.activeCount;i++){game.effects.update(.05,i*.05);game.renderer.render();await frame();}await frames(3);check(JSON.stringify(counts())===JSON.stringify(baseline),`Cast ${cast+1}: warmed scene/GPU/subscription baseline`);}lines.push('COUNTS '+JSON.stringify({baseline,after:counts()}));}
  key('KeyW');await frames(60);check(game.player.visual.animationState==='Run','WASD velocity-blended locomotion');game.abilities.update(20);check(game.abilities.cast(context()),'Cast while moving');await frames(6);check(game.player.visual.motion?.castPhase!=='READY'&&game.player.visual.animationState==='Run','Upper-body spatial slash preserves locomotion');key('ShiftLeft');await frames(60);check(game.player.visual.animationState==='Run','Sprint remains live');key('KeyW','keyup');key('ShiftLeft','keyup');game.effects.update(120,120);await frames(180);check(game.player.visual.animationState==='Idle'&&game.player.visual.motion?.castPhase==='READY','Idle and gesture recovery');
  const aim=game.targeting.aimDirection.clone();renderer.domElement.dispatchEvent(new MouseEvent('mousemove',{buttons:2,movementX:20,movementY:8,bubbles:true}));await frames(12);check(!aim.equals(game.targeting.aimDirection),'Camera/targeting responds to mouse');key('F3');key('F3','keyup');await frames();check(!root.querySelector<HTMLElement>('.ocean-editor')!.hidden,'F3 ocean/character diagnostics');
  check(JSON.stringify(game.abilities.slots.slice(0,31))===oldSlots,'Original 31 slots/shortcuts unchanged');
  game.effects.dispose();game.dispose();disposed=true;check(renderer.info.memory.geometries===0&&renderer.info.memory.textures===0&&game.settings.subscriberCount===0,'Complete game teardown frees GPU resources and subscriptions');check(errors===0,'RIFTREAVER BROWSER COMPLETE');
}catch(e){check(false,String(e));if(!disposed){game.dispose();disposed=true;}}
if(initialFavorites===null)localStorage.removeItem('elemental-favorites');else localStorage.setItem('elemental-favorites',initialFavorites);
report.dataset.complete='true';report.textContent=lines.join('\n');window.addEventListener('pagehide',()=>{if(!disposed)game.dispose();});

