import { test, expect } from '@playwright/test';
import { BufferGeometry, Mesh, InstancedMesh, PerspectiveCamera, Scene, Vector3 } from 'three';
import type { AbilityCastContext } from '../src/abilities/Ability';
import { Riftreaver, riftTarget } from '../src/abilities/riftreaver/Riftreaver';
import { RIFT_DEFAULTS, RIFT_CAST, riftQuality, riftPhase, validateRiftConfig } from '../src/abilities/riftreaver/RiftreaverConfig';
import { createRiftResources, disposeRiftResources, riftBoundary } from '../src/abilities/riftreaver/RiftGeometry';
import { RiftreaverEffect } from '../src/abilities/riftreaver/RiftreaverEffect';
import { EffectManager } from '../src/effects/EffectManager';
import { Player } from '../src/player/Player';
import { GraphicsSettings } from '../src/quality/GraphicsSettings';
import { QUALITY_PRESETS } from '../src/quality/QualityPreset';
import { TargetingSystem } from '../src/targeting/TargetingSystem';
import { WaterInteractionManager } from '../src/world/water/WaterInteractionManager';
import { AbilityManager } from '../src/abilities/AbilityManager';
import { matchesSpell, spellCategory } from '../src/ui/SpellCatalog';
function context(distance=28):AbilityCastContext {const scene=new Scene(),player=new Player(scene),water=new WaterInteractionManager();water.setHeightSampler((x,z)=>.2+Math.sin(x*.1+z*.2)*.1);const target=new Vector3(0,0,-distance);return {scene,player,water,camera:new PerspectiveCamera(),origin:new Vector3(0,1.3,0),direction:new Vector3(0,0,-1),playerForward:new Vector3(0,0,-1),cameraForward:new Vector3(0,0,-1),targetPoint:target,groundTarget:target,targeting:new TargetingSystem(scene),quality:new GraphicsSettings(),effectManager:new EffectManager(),time:0};}
function clean(c:AbilityCastContext,a:Riftreaver){c.effectManager.dispose();a.dispose();c.player.dispose();c.water?.dispose();c.targeting.dispose();c.quality.dispose();}
function geometry(g:BufferGeometry,closed=true){const p=g.getAttribute('position'),n=g.getAttribute('normal'),a=new Vector3(),b=new Vector3(),c=new Vector3(),cross=new Vector3(),delta=new Vector3();let minimum=Infinity,normalError=0,volume=0;const edges=new Map<string,number>();const key=(v:Vector3)=>v.toArray().map(x=>x.toFixed(5)).join(',');
  for(let i=0;i<p.count;i+=3){a.fromBufferAttribute(p,i);b.fromBufferAttribute(p,i+1);c.fromBufferAttribute(p,i+2);minimum=Math.min(minimum,cross.subVectors(b,a).cross(delta.subVectors(c,a)).lengthSq());volume+=a.dot(cross.copy(b).cross(c))/6;for(const [v,w] of [[a,b],[b,c],[c,a]]){const k=[key(v),key(w)].sort().join('|');edges.set(k,(edges.get(k)??0)+1);}}
  for(let i=0;i<n.count;i++)normalError=Math.max(normalError,Math.abs(delta.fromBufferAttribute(n,i).length()-1));expect(minimum).toBeGreaterThan(1e-12);expect(normalError).toBeLessThan(1e-5);expect([...p.array,...n.array].every(Number.isFinite)).toBe(true);expect(g.boundingSphere!.radius).toBeGreaterThan(0);expect(g.boundingBox!.isEmpty()).toBe(false);if(closed){expect([...edges.values()].every(x=>x===2)).toBe(true);expect(volume).toBeGreaterThan(0);}}
test('Three quality tiers have closed volumetric hard facets, continuous boundaries, finite nondegenerate membrane and sharp slashes',()=>{const r=createRiftResources(RIFT_DEFAULTS);for(const tier of r.tiers){[tier.left,tier.right,tier.glowLeft,tier.glowRight].forEach(g=>geometry(g));geometry(tier.interior,false);expect(tier.left.boundingBox!.max.z-tier.left.boundingBox!.min.z).toBeGreaterThan(.3);}geometry(r.slash);r.shards.forEach(g=>geometry(g));for(let i=0;i<60;i++){const a=riftBoundary(i/60,-1),b=riftBoundary((i+1)/60,-1);expect(Math.hypot(...a.map((v,j)=>v-b[j]))).toBeLessThan(3);}expect(r.slash.boundingBox!.max.z-r.slash.boundingBox!.min.z).toBeGreaterThan(.15);disposeRiftResources(r);});
test('Typed config rejects invalid values, bounded quality and timeline preserve exactly three slashes',()=>{expect(()=>validateRiftConfig({height:NaN})).toThrow();expect(validateRiftConfig({width:999}).width).toBe(10);const q=Object.values(QUALITY_PRESETS).map(riftQuality);expect(q.map(x=>x.shards)).toEqual([30,60,105]);expect(q.map(x=>x.particles)).toEqual([280,680,1300]);expect(riftPhase(.1,1,RIFT_DEFAULTS)).toBe('incision');expect(riftPhase(.5,1,RIFT_DEFAULTS)).toBe('travel');expect(riftPhase(1.4,1,RIFT_DEFAULTS)).toBe('opening');expect(riftPhase(4.4,1,RIFT_DEFAULTS)).toBe('collapse');expect(riftPhase(6.5,1,RIFT_DEFAULTS)).toBe('complete');});
test('Registry, unbound selection, void filtering, search, range and cooldown use existing systems',()=>{const c=context(),a=new Riftreaver(),m=new AbilityManager();m.registry.register(a);m.selectAbility(a.id);expect(m.selectedAbility?.id).toBe(a.id);expect(m.slots[m.selectedIndex].code).toBe('');expect(spellCategory(a)).toBe('SHADOW / DARK');for(const s of ['rift','scar','reality','dimensional','void'])expect(matchesSpell(a,s,'SHADOW / DARK')).toBe(true);expect(m.cast(c)).toBe(true);expect(m.getCooldownById(a.id)).toBe(10);expect(m.cast(c)).toBe(false);m.dispose();clean(c,a);});
test('Target uses safe snapshot, ocean height, maximum ground range, camera fallback and invalid origin rejection',()=>{const c=context(100),target=riftTarget(c)!;expect(Math.hypot(target.x-c.origin.x,target.z-c.origin.z)).toBeCloseTo(55);expect(target.y).toBeCloseTo(c.water!.getSurfaceHeight(target.x,target.z));expect(c.targetPoint.z).toBe(-100);c.targetPoint.x=NaN;expect(riftTarget(c)!.toArray().every(Number.isFinite)).toBe(true);c.origin.z=NaN;expect(riftTarget(c)).toBeNull();clean(c,new Riftreaver());});
test('Hand-fired incision travels at 55m/s, snapshots target, opens only after arrival and hits three times in sequence',()=>{const c=context(),r=createRiftResources(RIFT_DEFAULTS),e=new RiftreaverEffect(c,r,RIFT_DEFAULTS);e.activate(c,riftTarget(c)!);e.update(.15);expect(e.position.distanceTo(c.player.visual.getRightHandWorldPosition())).toBeLessThan(1e-8);e.update(.15);const p=e.position.clone();e.update(.1);expect(e.position.distanceTo(p)).toBeCloseTo(5.5);expect(e.fracture.visible).toBe(false);c.targetPoint.set(99,0,99);while(e.phase==='travel')e.update(.025);expect(e.target.z).toBeLessThan(-20);expect(e.fracture.visible).toBe(true);const hitOrder:number[]=[];for(let i=0;i<200;i++){const old=[...e.slashes.hit];e.update(.025);e.slashes.hit.forEach((v,j)=>{if(v&&!old[j])hitOrder.push(j);});e.root.traverse(o=>{if(o instanceof Mesh){expect(o.quaternion.toArray().every(Number.isFinite)).toBe(true);}if(o instanceof InstancedMesh)expect([...o.instanceMatrix.array].every(Number.isFinite)).toBe(true);});for(const u of [e.edge.uniforms,e.energy.uniforms,e.voidMaterial.uniforms,e.particles.material.uniforms])expect(Object.values(u).every(v=>Number.isFinite(v.value))).toBe(true);}expect(hitOrder).toEqual([0,1,2]);expect(c.water!.emitted).toBe(6);e.destroy();expect(c.water!.activeCount).toBe(0);disposeRiftResources(r);clean(c,new Riftreaver());});
test('Twenty complete casts, live tiers and two bounded leases return to warmed resources without scene, water or subscription leaks',()=>{const c=context(55),a=new Riftreaver(),base=c.scene.children.length,subs=c.quality.subscriberCount;let oldGeometries=0;for(let k=0;k<20;k++){c.quality.setPreset(k%3===0?'LOW':k%3===1?'MEDIUM':'MAX');expect(a.cast(c)).toBe(true);expect(()=>a.configure({width:4})).toThrow();let maximum=0;for(let i=0;i<150;i++){c.effectManager.update(.05,i*.05);maximum=Math.max(maximum,c.effectManager.particleCount);if(i===30)c.quality.setPreset(k%2?'LOW':'MAX');}expect(maximum).toBeLessThanOrEqual(1300);expect(c.effectManager.activeCount).toBe(0);expect(c.scene.children.length).toBe(base);expect(c.quality.subscriberCount).toBe(subs);expect(c.water!.activeCount).toBe(0);let n=0;c.scene.traverse(o=>{if(o instanceof Mesh)n++;});if(k)expect(n).toBe(oldGeometries);oldGeometries=n;}expect(a.cast(c)).toBe(true);expect(a.cast(c)).toBe(true);expect(a.cast(c)).toBe(false);expect(a.activeCount).toBe(RIFT_CAST.maximumActive);c.effectManager.update(120,120);expect(a.activeCount).toBe(0);a.configure({width:6});clean(c,a);});

test('Idle shader preparation compiles bounded detached prototypes and cancels safely without disposing shared geometry',async()=>{
 const { RiftWarmup }=await import('../src/abilities/riftreaver/RiftWarmup');const callbacks=new Map<number,()=>void>();let serial=0,compiles=0,cancels=0,sharedDisposals=0;
 const previous=Object.getOwnPropertyDescriptor(globalThis,'window');Object.defineProperty(globalThis,'window',{configurable:true,value:{requestIdleCallback:(f:()=>void)=>{callbacks.set(++serial,f);return serial;},cancelIdleCallback:(id:number)=>{callbacks.delete(id);cancels++;}}});
 const r=createRiftResources(RIFT_DEFAULTS),settings=new GraphicsSettings();r.shards[0].addEventListener('dispose',()=>sharedDisposals++);
 try{const renderer={compile:(s:Scene)=>{expect(s.children.length).toBe(2);compiles++;}} as unknown as import('three').WebGLRenderer;
   const warm=new RiftWarmup(r,RIFT_DEFAULTS,renderer,new PerspectiveCamera(),new Scene(),settings);expect(callbacks.size).toBe(1);const callback=callbacks.get(1)!;callbacks.delete(1);callback();expect(compiles).toBe(1);expect(callbacks.size).toBe(1);warm.dispose();warm.dispose();expect(cancels).toBe(1);expect(sharedDisposals).toBe(0);callback();expect(compiles).toBe(1);
 }finally{if(previous)Object.defineProperty(globalThis,'window',previous);else Reflect.deleteProperty(globalThis,'window');disposeRiftResources(r);settings.dispose();}
 expect(sharedDisposals).toBe(1);
});
