import {AdditiveBlending,DoubleSide,ShaderMaterial} from 'three';
export function clockMaterial(bright=false):ShaderMaterial{
  return new ShaderMaterial({transparent:true,depthWrite:!bright,side:DoubleSide,...(bright?{blending:AdditiveBlending}:{}),uniforms:{uTime:{value:0},uBlue:{value:0},uDetail:{value:2},uBright:{value:bright?1:0}},
    vertexShader:`attribute vec4 aTemporal;varying vec3 vP,vW,vN;varying vec2 vUv;varying vec4 vLife;void main(){vLife=aTemporal;vUv=uv;vP=position;vec4 w=modelMatrix*instanceMatrix*vec4(position,1.);vW=w.xyz;vN=normalize(mat3(modelMatrix)*mat3(instanceMatrix)*normal);gl_Position=projectionMatrix*viewMatrix*w;}`,
    fragmentShader:`varying vec3 vP,vW,vN;varying vec2 vUv;varying vec4 vLife;uniform float uTime,uBlue,uDetail,uBright;void main(){vec3 n=normalize(vN),eye=normalize(cameraPosition-vW);float fres=pow(1.-abs(dot(n,eye)),2.5),spec=pow(max(0.,dot(reflect(-normalize(vec3(-.4,.85,.3)),n),eye)),42.);float engrave=pow(max(0.,sin(vUv.x*41.+vUv.y*17.)),16.);float flow=pow(max(0.,sin(vUv.x*22.-uTime*3.+vLife.y*5.)),8.);float transition=clamp(uBlue*.9+.1*sin(vP.y*4.-uTime*.2)*uBlue,0.,1.);vec3 metal=mix(vec3(.45,.28,.065),vec3(.055,.26,.4),transition);vec3 edge=mix(vec3(1.,.88,.53),vec3(.47,.91,1.),transition);float light=.35+.65*abs(dot(n,normalize(vec3(-.4,.85,.3))));vec3 col=metal*light+edge*(fres*.33+spec*.6+engrave*.09*vLife.z+flow*.12*vLife.z);if(uBright>.5)col=mix(edge,vec3(.97,.99,1.),fres*.55+flow*.2)*(.7+vLife.z*.25);gl_FragColor=vec4(col,vLife.x*(uBright>.5?.8:1.));}`});
}
export function temporalWaveMaterial():ShaderMaterial{
  return new ShaderMaterial({transparent:true,depthWrite:false,side:DoubleSide,blending:AdditiveBlending,uniforms:{uTime:{value:0},uFade:{value:0}},
    vertexShader:`varying vec2 vUv;varying vec3 vW;uniform float uTime;void main(){vUv=uv;vec3 p=position*(1.+sin(uv.x*48.+uTime*3.)*sin(uv.y*16.)*.018);vec4 w=modelMatrix*vec4(p,1.);vW=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,
    fragmentShader:`varying vec2 vUv;varying vec3 vW;uniform float uTime,uFade;void main(){vec3 n=normalize(cross(dFdx(vW),dFdy(vW)));float edge=pow(1.-abs(dot(n,normalize(cameraPosition-vW))),2.);float ticks=pow(max(0.,cos(vUv.x*75.398)),18.);float bands=pow(max(0.,sin(vUv.y*59.-uTime*6.)),16.);vec3 col=mix(vec3(.66,.46,.15),vec3(.4,.89,1.),edge*.65+bands*.25);gl_FragColor=vec4(col,(edge*.38+bands*.19+ticks*.1)*uFade);}`});
}
